In [3]:
import pandas as pd

In [4]:
# Concatenation

df1 = pd.DataFrame({
    "id" : [1, 2, 3],
    "name" : ["Adam", "Eve", "Bob"]
})

df2 = pd.DataFrame({
    "id": [4, 5, 6],
    "name" : ["Charlie", "Fester", "Gigi"]
})

In [5]:
df1

   id  name
0   1  Adam
1   2   Eve
2   3   Bob

In [6]:
df2

   id     name
0   4  Charlie
1   5   Fester
2   6     Gigi

In [7]:
pd.concat([df1, df2]) # row

   id     name
0   1     Adam
1   2      Eve
2   3      Bob
0   4  Charlie
1   5   Fester
2   6     Gigi

In [9]:
pd.concat([df1, df2], ignore_index=True) #override original labels

   id     name
0   1     Adam
1   2      Eve
2   3      Bob
3   4  Charlie
4   5   Fester
5   6     Gigi

In [10]:
pd.concat([df1, df2], axis=1) # col

   id  name  id     name
0   1  Adam   4  Charlie
1   2   Eve   5   Fester
2   3   Bob   6     Gigi