In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("GlobalAirQuality.csv")

In [5]:
#Filtering of Data

aqi_data = df[ (df["aqi"] > 100) & (df["temperature"] > 30) ][["city", "aqi"]]

In [6]:
aqi_data

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]

In [9]:
aqi_data.iloc[0] #by default idx starts from 0

city    New York
aqi          155
Name: 6, dtype: object

In [8]:
aqi_data.loc[6]

city    New York
aqi          155
Name: 6, dtype: object

In [10]:
#Filtering data using Query()

df.query("aqi > 200")

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
745,2025-11-05 19:25:17.554219,GB,London,51.507,-0.128,107.144,43.819,13.389,4.601,21.680,0.890,214,19.055,66.245,1.637
8941,2025-11-17 07:25:17.554219,JP,Osaka,34.694,135.502,102.142,95.204,41.688,7.806,28.951,0.753,204,15.277,76.131,4.586
12956,2025-11-19 14:25:17.554219,NZ,Auckland,-36.848,174.763,44.824,66.657,90.019,3.637,41.311,0.849,225,14.872,63.319,0.958
14555,2025-11-11 05:25:17.554219,PH,Manila,14.600,120.984,103.023,66.678,43.284,2.167,48.250,0.849,206,11.027,63.522,7.635
17458,2025-11-12 04:25:17.554219,FI,Helsinki,60.170,24.938,14.329,51.173,81.111,7.725,61.160,1.383,202,34.420,26.061,3.771
17529,2025-11-15 03:25:17.554219,FI,Helsinki,60.170,24.938,115.683,81.714,54.764,6.687,39.552,0.685,231,25.795,87.839,6.705
17815,2025-11-12 01:25:17.554219,CH,Zurich,47.377,8.542,54.805,39.178,81.406,10.241,46.579,0.498,203,20.883,70.201,3.500

In [12]:
df.query("aqi > 200 & temperature < 30")[["city", "aqi"]]

           city  aqi
745      London  214
8941      Osaka  204
12956  Auckland  225
14555    Manila  206
17529  Helsinki  231
17815    Zurich  203

In [13]:
#variables in query()
aqi_val = 200
df.query("aqi > @aqi_val & temperature < 30")[["city", "aqi"]]

           city  aqi
745      London  214
8941      Osaka  204
12956  Auckland  225
14555    Manila  206
17529  Helsinki  231
17815    Zurich  203